NOMBRE=Inventario PRC
URL=https://example.com/inventario
ID=com.juan.inventarioprc
ORIENTACION=portrait
VERSION=1.0
UBICACION=false
MICROFONO=false
CAMARA=true
NOTIFICACIONES=true
DESCARGAS=true
ZOOM=false
PANTALLA_COMPLETA=true
ENLACES_EXTERNOS=true
