NOMBRE=Control PRC
URL=https://example.com/control
ID=com.juan.controlprc
ORIENTACION=horizontal
VERSION=1.0
UBICACION=true
MICROFONO=true
CAMARA=true
NOTIFICACIONES=true
DESCARGAS=true
ZOOM=false
PANTALLA_COMPLETA=true
ENLACES_EXTERNOS=true
