NOMBRE=14 DCM
URL=https://dania123456789123456-del.github.io/Libro-PDF/
ID=com.juan.miweb
ORIENTACION=landscape
VERSION=1.0
UBICACION=true
MICROFONO=true
CAMARA=true
NOTIFICACIONES=true
DESCARGAS=true
ZOOM=false
PANTALLA_COMPLETA=true
ENLACES_EXTERNOS=true
